### ISSUE TITLE
大佬 能否新增select 自定义value

### ISSUE THREAD

**Issue by CHENJKNB** [joyceworks/dynamic-form-react#10]
大佬 能否新增select 自定义value
![image](https://user-images.githubusercontent.com/18523983/119948949-f08d7200-bfcb-11eb-888c-415a8636aef5.png)

**Comment by iamppz** [comment]
这个暂时不考虑实现，你可以复制重命名一份`SelectCell`修改Config文件，然后以自定义组件的形式传入：
```typescript
<Form
  customCells={[
    {
      type: "customSelect",
      cell: CustomSelect,
      name: "Custom Select",
      config: SelectWrapperCellConfig,
    }
  ]}
/>
```
